### ISSUE TITLE
Tool landmark_registration_ls is not accessible at usegalaxy.eu

### ISSUE THREAD

**Issue by qgao-hd** [BMCV/galaxy-image-analysis#23]
Hello @bgruening , thanks for merging the PR of adding two new tools. However, the tool landmark_registration_ls is not accessible at usegalaxy.eu, while the other one works perfectly.

Maybe the reason is that it uses the same tool name as the tool landmark_registration (despite of a unique tool IDs)?

**Comment by bgruening** [comment]
Can you please check again? 
I see this here: 
https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/imgteam/landmark_registration_ls/ip_landmark_registration_ls/0.0.1

**Comment by qgao-hd** [comment]
> Can you please check again?
> I see this here:
> https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/imgteam/landmark_registration_ls/ip_landmark_registration_ls/0.0.1

Thanks. Now I can find this tool through search, but it did not work at least one hour ago. So weird.

**Comment by bgruening** [comment]
What means it does not work? Do you get an error?

**Comment by qgao-hd** [comment]
> What means it does not work? Do you get an error?

I meant I could not find landmark_registration_ls through search (top-left corner). Now this tool is searchable.

**Comment by bgruening** [comment]
Ok, cool, so its works now :)

Thanks a lot @qgao-hd
