### ISSUE TITLE
Updated version of the tool "points_association_nn" on usegalaxy.eu

### ISSUE THREAD

**Issue by qgao-hd** [BMCV/galaxy-image-analysis#28]
Hi @bgruening , thanks for merging the updates of the tool "points_association_nn". I have seen that this tool has been updated to version 0.02 in the Galaxy tool shed, but it is still 0.01 on usegalaxy.eu. 

Will tool updates on usegalaxy.eu be executed also on Saturdays like adding new tools? If so, is it possible to have this tool updated on usegalaxy.eu sooner? Waiting until the weekend seems slightly too long to us as we would like to include this tool and a related workflow in our new paper to be submitted within this week.

Thanks!

**Comment by bgruening** [comment]
I triggered a new install. Please check later today or the evening.

**Comment by qgao-hd** [comment]
> I triggered a new install. Please check later today or the evening.

I've seen it. I also showed the new workflow (based on this updated tool) to our partners and they are very happy.  Thank you!

**Comment by bgruening** [comment]
@qgao-hd is this workflow open? Can you share it are write a blog post about it ... for the de.NBI funding stuff but also to give you some credits?

**Comment by qgao-hd** [comment]
> @qgao-hd is this workflow open? Can you share it are write a blog post about it ... for the de.NBI funding stuff but also to give you some credits?

Sure, we would share it, but perhaps not at the moment. Our partners are testing it now and we plan to publish this workflow on usegalaxy.eu once the paper gets accepted. Could you wait for some time ... hopefully not too long? @bgruening

**Comment by bgruening** [comment]
Sure, I just hope we remember :-)

Rock on!
