### ISSUE TITLE
Slash Command Dispatch workflow run failed for master branch

### ISSUE THREAD

**Issue by kostrykin** [BMCV/galaxy-image-analysis#55]
I got a notification saying

>  Slash Command Dispatch workflow run failed for master branch 

immediately after commenting on [this PR](https://github.com/BMCV/galaxy-image-analysis/pull/54#issuecomment-1592733427).

Clicking on the notification redirects me to [this action](https://github.com/BMCV/galaxy-image-analysis/actions/runs/5277359286). As far as I see, some action was supposed to be triggered by my comment, but did not. Is there something misconfigured and might this be related to the failing PR?

**Comment by bgruening** [comment]
I think we need to update our CI integration here. Best is to take it from IUC: https://github.com/galaxyproject/tools-iuc/tree/main/.github/workflows

**Comment by kostrykin** [comment]
Never worked with GitHub actions before. Is it fine to just copy the files, or is there anything that needs to be adapted?

**Comment by bgruening** [comment]
Yes, just copy the files, 3 lines needs to be changed, but I can do that.

**Comment by kostrykin** [comment]
@bgruening PR #57 brings the new files, but I think **four** lines of code needed to be changed (not three), see cfab54420a1af8b8595aa911e70fe3067e0f7a18. Can you maybe briefly review the changes?

**Comment by bgruening** [comment]
Three was just a guess ;) Too old to remember exact numbers ;)

**Comment by bgruening** [comment]
We do not use slash here in this repo (yet) and the token as missing. I removed it. We can add it later if we need it.

Thanks @kostrykin
