### ISSUE TITLE
`planemo test` fails for any tool

### ISSUE THREAD

**Issue by kostrykin** [BMCV/galaxy-image-analysis#59]
I was experiencing some inconsistent behavior when using `planemo test` for a tool I am developing. In search for the cause I had to remove `~/miniconda3` on my system, which was then re-created by the next invocation of `planemo test`.

When running `planemo test` now, for example, for the tool _segmetrics_, the following output is obtained and repeated a few times with some variations regarding the parameters passed to `conda create`:
```
galaxy.tool_util.deps.conda_util DEBUG 2023-06-19 16:13:33,607 [pN:main.1,p:1021725,tN:LocalRunner.work_thread-0] Executing command: ~/miniconda3/bin/conda create -y --quiet --strict-channel-priority --experimental-solver libmamba --override-
channels --channel conda-forge --channel bioconda --channel defaults --name mulled-v1-138080b4d40419e12a6a019e79f27ae713ae4ee1e04039908a3b046c06674243 segmetrics=1.4 pandas=0.23.4
galaxy.tool_util.deps.conda_util DEBUG 2023-06-19 16:13:33,880 [pN:main.1,p:1021725,tN:LocalRunner.work_thread-0] Executing command: ~/miniconda3/bin/conda create -y --quiet --experimental-solver libmamba --override-channels --channel conda-f
orge --channel bioconda --channel defaults --name mulled-v1-138080b4d40419e12a6a019e79f27ae713ae4ee1e04039908a3b046c06674243 segmetrics=1.4 pandas=0.23.4
galaxy.tool_util.deps.resolvers.conda DEBUG 2023-06-19 16:13:34,152 [pN:main.1,p:1021725,tN:LocalRunner.work_thread-0] Removing failed conda install of [CondaTarget[segmetrics,version=1.4], CondaTarget[pandas,version=0.23.4]]
galaxy.tool_util.deps.conda_util DEBUG 2023-06-19 16:13:34,152 [pN:main.1,p:1021725,tN:LocalRunner.work_thread-0] Executing command: ~/miniconda3/bin/conda create -y --quiet --strict-channel-priority --experimental-solver libmamba --override-
channels --channel conda-forge --channel bioconda --channel defaults --name __segmetrics@1.4 segmetrics=1.4
```

The creation of the environment ultimately fails.

Manually repeating the command reported above yields the error causing the failure:

```
~/miniconda3/bin/conda create --strict-channel-priority --experimental-solver libmamba --override-channels --channel conda-forge --channel bioconda --channel defaults --name test pandas
```
```
usage: conda create [-h] [--clone ENV] (-n ENVIRONMENT | -p PATH) [-c CHANNEL] [--use-local] [--override-channels] [--repodata-fn REPODATA_FNS] [--experimental {jlap,lock}] [--strict-channel-priority] [--no-channel-priority]
                    [--no-deps | --only-deps] [--no-pin] [--copy] [-C] [-k] [--offline] [-d] [--json] [-q] [-v] [-y] [--download-only] [--show-channel-urls] [--file FILE] [--no-default-packages] [--solver {classic} | --experimental-solver {classic}]
                    [--dev]
                    [package_spec ...]
conda create: error: argument --experimental-solver: invalid choice: 'libmamba' (choose from 'classic')
```

Without the `--experimental-solver libmamba` flag, the above command works. Can `planemo test` somehow be told not to use this flag? Removing `~/.planemo` on my system to make sure it is reset to a clean state does not make a change.

Note that this isn't related to any particular tool. Besides of _segmetrics_, I also tried `planemo test` for the tools _2d_auto_threshold_, _2d_feature_extraction_, and _overlay_images_, which all yield the behavior described above.

Is this maybe related to https://github.com/galaxyproject/galaxy/issues/16124?

**Comment by kostrykin** [comment]
This issue resolved by itself after re-creating the Conda environment which I use to run `planemo test`. No idea, though, what was going on here. Will leave this here for the record in case someone else stumbles into the same issue.

**Comment by bgruening** [comment]
Also try to run planemo test --biocontainers .... This will be more comparable with the CI
