### ISSUE TITLE
python: can't open file (No such file or directory)

### ISSUE THREAD

**Issue by kostrykin** [BMCV/galaxy-image-analysis#67]
When running the recent tool versions updated by #65 and #66, an error occurs:

> python: can't open file '/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/imgteam/superdsm/700ae37e5c69/superdsm/run-superdsm.py': [Errno 2] No such file or directory

and

> python: can't open file '/opt/galaxy/shed_tools/toolshed.g2.bx.psu.edu/repos/imgteam/count_objects/5bf8eb50b280/count_objects/count_objects.py': [Errno 2] No such file or directory

respectively. Maybe the web handlers are out of sync again? @bgruening 

Here is a link to the errors: https://usegalaxy.eu/u/e26918e6b1264c81874871c01e988195/h/unnamed-history-1

**Comment by kostrykin** [comment]
Started working, out of a sudden. Will leave this here for the record.

**Comment by bgruening** [comment]
Oh yeah, maybe you hit the timeslot where the auto-install was running but no restart actually happened.
