### ISSUE TITLE
overlay_images for segmentation masks should output png

### ISSUE THREAD

**Issue by thawn** [BMCV/galaxy-image-analysis#75]
currently, when I use overlay_images to overlay an image with a segmentation mask, the output is tiff. This means I cannot view the result in the browser without converting it to png first.

since overlays of masks and images are only used for visualization, it would make sense to output png instead of tiff by default

**Comment by bgruening** [comment]
@thawn do you know about any lightweight JS-only visualization that can display tiff?

**Comment by thawn** [comment]
I just found [geotiffs]{https://geotiffjs.github.io/). Looks promising. haven't tried it myself, though.

**Comment by kostrykin** [comment]
I think that PNG is the more appropriate format for visualization purposes, since it is more widely supported by presentation media (web browsers, so in case you want to put the image on a web site, you can use it directly, text document editing systems like LaTeX, etc.). In that sense, it also is more appropriate for segmentation overlays.

But having the ability to view Tiffs directly in the web browser (I think where [this](#issuecomment-1802546508) was pointing to) would still be *hugely* convenient. How about automatic conversion of Tiffs (to, e.g., PNG) on server-side, would that be too much of an overhead?

**Comment by bgruening** [comment]
Galaxy has a concept of "data providers" that can convert, and stream data to a visualization. But I guess its not needed if we integrate geotiffs into Galaxy. Which should be doable. See examples:

* https://github.com/galaxyproject/galaxy/pull/7888/
* https://github.com/galaxyproject/galaxy/pull/13771
* https://github.com/galaxyproject/galaxy/pull/16187

**Comment by kostrykin** [comment]
Thanks for the examples.

In Galaxy, PNGs can be viewed *directly* by clicking the "eye" icon of a history item. As far as I see, the FITS visualizer as well as the 3D PCA visualizer work differently, they must be invoked through the "Visualize" tab of Galaxy (I couldn't deduce how the OpenLayers visualization works). This is a *detour*, and I'm not sure what the UX paradigm in Galaxy is, but to me it seems more natural to visualize TIFFs more directly, like PNGs, just by clicking the eye icon (also to be more consistent in that regard).

In the case that we agree on this, does that mean that [data providers](https://galaxyproject.org/data-providers/) are the road to take, or can this still be accomplished using JS?

**Comment by bgruening** [comment]
That it is functioning currently only with the visualize button and not via the eye icon does not mean that it needs to stay like that. We have discussed several times that the default visualisation (the one via the eye icon) should be configurable per datasets and it would be possible to invoke e.g. the PDB-3D viewer directly via the eye icon.
For ITs we are already doing this. 

I think we should work towards this direction, offering fancy Vis via the eye icon and offering options to opt-out and show the boring text visualisations (in the case of PDB).

**Comment by kostrykin** [comment]
I think discussion is obsolete now that we have https://github.com/galaxyproject/galaxy/pull/17553 and https://github.com/galaxyproject/galaxy/pull/17554.
