### ISSUE TITLE
Tools to be marked as hidden/deprecated

### ISSUE THREAD

**Issue by kostrykin** [BMCV/galaxy-image-analysis#93]
The following tools / tool versions should be marked as hidden and deprecated:
- [x] All revisions of `2d_split_binaryimage_by_watershed`,
  see https://github.com/usegalaxy-eu/usegalaxy-eu-tools/pull/647
- [x] Revision `7989264b5780` of `segmetrics`, corresponding to the tool version `1.4.0-1`,
  see https://github.com/BMCV/galaxy-image-analysis/pull/88
- [x] Revisions `4b6c2135e547` and `b32f5368e279` of `bioformats2raw` due to the bug described in https://github.com/BMCV/galaxy-image-analysis/pull/102
- [ ] Revision `7db4fc31dbee` of `ip_threshold`, corresponding to the tool version `0.18.1+galaxy0`, see https://github.com/BMCV/galaxy-image-analysis/pull/112
- [x] The tool `2d_local_threshold` is already marked as deprecated, but not hidden.
- [x] The `curl_post` tool should be marked deprecated.
- [x] The `points2binaryimage` tool should be marked as deprecated and hidden.

**Comment by bgruening** [comment]
The one that is not ticked off I could not find, it should not be installed anymore.

**Comment by kostrykin** [comment]
> The one that is not ticked off I could not find, it should not be installed anymore.

Thanks!

With `ip_threshold` I was referring to the tool ID in the XML: https://github.com/BMCV/galaxy-image-analysis/blob/2266053985e3ce39b28d3601d585c3669833a807/tools/2d_auto_threshold/auto_threshold.xml#L1

So this is this tool: https://toolshed.g2.bx.psu.edu/repository?repository_id=a74ca2106a7a2073

**Comment by bgruening** [comment]
Yes, but I could not find the revision `7db4fc31dbee` is this tool still in Galaxy?

**Comment by kostrykin** [comment]
You are right, it is not on usegalaxy.eu anymore. Thanks again!

Just one more question. I assume that deprecation happens in the toolshed and hiding is done on Galaxy EU, right? If so, there is the tool `3d_tensor_feature_dimension_reduction` [in the toolshed](https://toolshed.g2.bx.psu.edu/view/imgteam/3d_tensor_feature_dimension_reduction/e8f64a98cbc6) but it is not installed on Galaxy EU (or maybe it's hidden, at least I couldn't find it). Can you please mark it as deprecated?
